### 測試雲端 Predict API
##POST https://sales-predictor-mb8q.onrender.com/api/predict/
POST http://127.0.0.1:8000/predict/
Content-Type: application/json

{
  "organic": 120,
  "a_campaign": 50,
  "b_campaign": 30
}